[package]
name = "zdiff"
version = "0.3.0"
edition = "2024"

[[bin]]
name = "zdiff-gui"
path = "src/gui/main.rs"

[lib]
name = "zdiff"

[dependencies]
eframe = { version = "0.33.3", default-features = false, features = [
    "default_fonts",
    "accesskit",
    "glow",
    "serde",
    "persistence"
] }
serde = { version = "1.0.48", features = ["derive"], optional = true}
serde_json = "1.0.48"
egui_tiles =  {version = "0.14.1", features = ["serde"]}
log = "0.4.27"
rfd = "0.17.1"
egui_extras = { version = "0.33.3", features = ["image"] }
color-backtrace = { version = "0.7.2", optional = true }
blake3 = { version = "1.8.2", features = ["rayon", "mmap"] }
env_logger = "0.11.9"

[features]
default = ["serde"]
pretty-backtrace = ["dep:color-backtrace"]
serde = ["dep:serde"]
accesskit = []

[target.'cfg(target_os = "linux")'.dependencies]
eframe = { version = "0.33.3", features = ["wayland", "x11"] }
