[package]
name = "zhashdiff"
version = "1.2.0"
edition = "2024"
build = "build.rs"

[[bin]]
name = "zhashdiff-gui"
path = "src/gui/main.rs"

[dependencies]
eframe = { version = "0.33.3", default-features = false, features = [
    "default_fonts",
    "accesskit",
    "glow",
    "serde",
    "persistence"
] }
env_logger = "0.10"
serde = { version = "1.0.48", features = ["derive"], optional = true}
serde_json = "1.0.48"
egui_tiles =  {version = "0.14.1", features = ["serde"]}
log = "0.4.27"
blake3 = { version = "1.8.2", features = ["rayon", "mmap"] }
rfd = "0.17.1"
egui_extras = { version = "0.33.3", features = ["image"] }
crc32fast = "1.5.0"
tempfile = "3.25.0"
color-backtrace = { version = "0.7.2", optional = true }

[features]
default = ["serde"]
pretty-backtrace = ["dep:color-backtrace"]
serde = ["dep:serde"]
accesskit = []

[target.'cfg(target_os = "linux")'.dependencies]
eframe = { version = "0.33.3", features = ["wayland", "x11"] }